package com.example.sergi.soaptemp.WS;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 31-12-2015
//
//---------------------------------------------------



public interface IServiceEvents
{
    public void Starting();
    public void Completed(OperationResult result);
}
